name: 'Terraform Plan'

on:
  pull_request:
    paths:
      - terraform/**

env:
  AWS_REGION: eu-west-2
  TF_VAR_aws_region: eu-west-2

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        env:
          TF_VAR_certificate_arn: ${{ secrets.CERTIFICATE_ARN }}
          TF_VAR_clash_royale_api_key: ${{ secrets.CLASH_ROYALE_API_KEY }}
        run: terraform plan -no-color -input=false